tasks:
  - init: yarn install && yarn run build
    command: yarn run start

vscode:
  extensions:
    - liviuschera.noctis@10.29.1:9li6UDhn574pZ/dwrYdPww==
    - dsznajder.es7-react-js-snippets@2.7.1:ot1GSdt45abTrr2DCAM42g==